name: Pre-release

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

permissions:
  contents: write # Required for creating releases

jobs:
  pre-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags for versioning

      - name: Get latest tag
        id: get_latest_tag
        shell: bash
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "Latest tag: $LATEST_TAG"

      - name: Increment patch version for pre-release
        id: set_version
        shell: bash
        run: |
          TAG_WITHOUT_V=${LATEST_TAG#v}
          MAJOR=$(echo $TAG_WITHOUT_V | cut -d. -f1)
          MINOR=$(echo $TAG_WITHOUT_V | cut -d. -f2)
          PATCH=$(echo $TAG_WITHOUT_V | cut -d. -f3)
          NEW_PATCH=$((PATCH + 1))
          VERSION="v$MAJOR.$MINOR.$NEW_PATCH-$(date +'%Y%m%d')"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "New pre-release version: $VERSION"

      - name: Create pre-release tag
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Pre-release ${{ env.VERSION }}"
          draft: false
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Success Message
        run: echo "✅ Pre-release ${{ env.VERSION }} created successfully!"
