name: Semantic Release

on:
  push:
    branches:
      - develop
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Configure Git credentials with PAT
        run: |
          git config --global user.name "semantic-release-bot"
          git config --global user.email "semantic-release@users.noreply.github.com"
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/AESInsight/Frontend.git

      - name: Run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: bunx semantic-release
